{
 "title": "Combined Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node_wifi_station_receive_packets_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Packets Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node_wifi_station_transmit_packets_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "node_wifi_station_signal", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Noise Floor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "node_wifi_station_noise", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Transmit Modulation Coding Scheme",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "node_wifi_station_transmit_mcs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Receive Modulation Coding Scheme",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "node_wifi_station_receive_mcs", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}